runtime: nodejs16

env_variables:
  env_variables:
  DB_USER: 'postgres'
  DB_HOST: '/cloudsql/ingka-pdpp-absence-dev:europe-west4:ppdh-absence-dev-db'
  DB_NAME: 'absenceDB'
  DB_PASSWORD: 'postgres1234'
  DB_PORT: '5432'
